### ISSUE TITLE
getting an error when trying to build tensorflow2.3-enh (and non enh) with rocm3.7

### ISSUE THREAD

**Issue by witeko** [ROCmSoftwarePlatform/tensorflow-upstream#1095] opened 2020-08-25 22:05 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 20.04 and rhel 8.2 (not 8.3 because it is a beta)
- TensorFlow installed from (source or binary): rocm-tensorflow 2.3 enhanced (and non-enh version), tf21 seems to work fine
- Python version: 3.8 (and other versions)
- Bazel version (if compiling from source): 3.1
- GCC/Compiler version (if compiling from source): 9.3.0
- GPU model and memory: 2 x radeon7

**Describe the current behavior**
Im getting random errors when building tensorflow with rocm3.7.
I can install whl package but when training models I also get random errors.

Example build errors:
"
ERROR: /root/home/tensorflow-upstream-r2.3/tensorflow/stream_executor/rocm/BUILD:280:1: undeclared inclusion(s) in rule '//tensorflow/stream_executor/rocm:rocm_helpers':
this rule is missing dependency declarations for the following files included by 'tensorflow/stream_executor/rocm/rocm_helpers.cu.cc':
  '/opt/rocm-3.7.0/hip/include/hip/hip_runtime.h'
  '/opt/rocm-3.7.0/hip/include/hip/hip_version.h'
  '/opt/rocm-3.7.0/hip/include/hip/hip_common.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/hip_runtime.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/hip_common.h'
  '/opt/rocm-3.7.0/hip/include/hip/hip_runtime_api.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/hip_runtime_api.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/host_defines.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/driver_types.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/hip_texture_types.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/channel_descriptor.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/hip_vector_types.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/texture_types.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/hip_surface_types.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/hip_ldg.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/hip_atomic.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/device_functions.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/math_fwd.h'
  '/opt/rocm-3.7.0/hip/include/hip/hip_vector_types.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/device_library_decls.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/llvm_intrinsics.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/surface_functions.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/texture_fetch_functions.h'
  '/opt/rocm-3.7.0/hip/include/hip/texture_types.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/ockl_image.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/texture_indirect_functions.h'
  '/opt/rocm-3.7.0/hip/include/hip/hip_texture_types.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/math_functions.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/hip_fp16_math_fwd.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/hip_memory.h'
  '/opt/rocm-3.7.0/hip/include/hip/library_types.h'
  '/opt/rocm-3.7.0/hip/include/hip/hcc_detail/library_types.h'
clang-11: warning: argument unused during compilation: '--hip-device-lib-path=/opt/rocm-3.7.0/lib' [-Wunused-command-line-argument]
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.

"

**Comment by witeko** [comment] 2020-08-26 18:36
The problem persists also when trying to build tensorflow in rocm/tensorflow:rocm3.7-tf2.3-dev

**Comment by jerryyin** [comment] 2020-08-28 20:24
Thanks for reporting. We have most recently updated a number of release branches since ROCm3.7 come out. Would you give a shot to the tip of those release branches? Or an alternative is to use the pre-built docker containers [here](https://hub.docker.com/repository/registry-1.docker.io/rocm/tensorflow/tags?page=1).

**Comment by witeko** [comment] 2020-08-28 20:48
@jerryyin I've already tried everything (including docker, and also different distros [rhel 8.2 and ubuntu 20.04]): rocm3.7 doesnt build for me with tf2.3(-enh). It builds and works fine with tf21. It builds with 2.2(-enh) but there are situations when it doesnt work properly (hangs my computer while training for example mobile net).

**Comment by jerryyin** [comment] 2020-08-28 20:54
Hey @sunway513 Could you comment on which branch did you use specifically to build the `rocm/tensorflow:rocm3.7-tf2.3-dev` image?

**Comment by witeko** [comment] 2020-08-28 21:04
@jerryyin , @sunway513, I think I've also checked all possible branches, theres no way around it - it doesnt work for me...

**Comment by sunway513** [comment] 2020-08-28 21:14
Hi @witeko , we've been using the following branch to build the public ROCm3.7 TF2.3 docker container:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/tree/r2.3-rocm-enhanced
The tensorflow source, bazel and all the dependencies were included there in the docker. 
After launching it, the following steps can rebuild it:
`cd ~/tensorflow && bash build_rocm_python3 `

**Comment by witeko** [comment] 2020-08-28 21:19
@sunway513 Ive tried it already, the same error. The problem is somewhere else apparently...driver? hardware (maybe different specs activate different bits in the code.?)

**Comment by sunway513** [comment] 2020-08-28 21:25
Our build machine doesn't have AMD GPUs resources. I wouldn't expect issues to rebuild the quoted TF branch inside that docker container. 
Did you made any code changes on TF?

**Comment by witeko** [comment] 2020-08-28 21:28
@sunway513 no code changes on my side.
hmm...nothing that should matter - for example I restrict the number of jobs for bazel with "-j 20" - thats the only "custom" stuff..

**Comment by jerryyin** [comment] 2020-08-28 22:36
Closing as not reproducible. If you continue to run into issues please reinstall ROCm 3.7.

In `rocm/tensorflow:rocm3.7-tf2.3-dev`, follow the instruction from @sunway513, do `cd ~/tensorflow && bash build_rocm_python3` and TF-rocm will be built fine.

**Closed as completed by jerryyin** 2020-08-28 22:36 UTC
