### ISSUE TITLE
Poor multi-gpu scaling

### ISSUE THREAD

**Issue by witeko** [ROCmSoftwarePlatform/tensorflow-upstream#345] opened 2019-03-09 22:49 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.10
- TensorFlow installed from (source or binary): tensorflow-rocm 1.13.1
- TensorFlow version (use command below): tensorflow-rocm 1.13.1
- Python version: 3.6
- ROCm/MIOpen version: newest
- GPU model and memory: 2x vega7 16gb, threadripper 1920x, 64gm ddr4

**Describe the current behavior**

TF_ROCM_FUSION_ENABLE=1 python tf_cnn_benchmarks.py --num_gpus=1 --batch_size=128 --model=resnet50 --use_fp16=1
Step	Img/sec	total_loss
1	images/sec: 407.8 +/- 0.0 (jitter = 0.0)	7.875
10	images/sec: 407.3 +/- 0.5 (jitter = 0.7)	7.959
20	images/sec: 406.4 +/- 0.5 (jitter = 1.2)	7.949
30	images/sec: 405.6 +/- 0.4 (jitter = 2.4)	7.945
40	images/sec: 404.3 +/- 0.5 (jitter = 3.6)	7.963
50	images/sec: 403.1 +/- 0.5 (jitter = 4.9)	7.709
60	images/sec: 402.0 +/- 0.6 (jitter = 5.3)	7.914
70	images/sec: 400.8 +/- 0.6 (jitter = 6.9)	7.842
80	images/sec: 399.6 +/- 0.6 (jitter = 7.9)	7.970
90	images/sec: 398.5 +/- 0.7 (jitter = 8.5)	7.802
100	images/sec: 397.4 +/- 0.7 (jitter = 9.4)	7.772

TF_ROCM_FUSION_ENABLE=1 python tf_cnn_benchmarks.py --num_gpus=2 --batch_size=128 --model=resnet50 --use_fp16=1
Step	Img/sec	total_loss
1	images/sec: 460.6 +/- 0.0 (jitter = 0.0)	7.938
10	images/sec: 456.5 +/- 14.8 (jitter = 28.5)	7.905
20	images/sec: 470.5 +/- 8.5 (jitter = 28.4)	7.883
30	images/sec: 465.7 +/- 7.3 (jitter = 28.1)	7.866
40	images/sec: 465.4 +/- 6.5 (jitter = 26.7)	7.944
50	images/sec: 461.5 +/- 6.0 (jitter = 35.0)	7.794
60	images/sec: 459.1 +/- 5.6 (jitter = 33.5)	7.868
70	images/sec: 458.9 +/- 5.1 (jitter = 35.0)	7.814
80	images/sec: 457.6 +/- 4.7 (jitter = 41.7)	7.806
90	images/sec: 456.7 +/- 4.5 (jitter = 43.7)	7.821
100	images/sec: 456.1 +/- 4.4 (jitter = 44.2)	7.790

**Describe the expected behavior**
I would expect scaling higher than 10-15%.

I looked into https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/92 but it didnt help

**Comment by witeko** [comment] 2019-03-09 23:11
OK, so the #92 did help me - I switched "Above 4G memory/ Crypto Currency mining"=ENABLED in BIOS and got:
TF_ROCM_FUSION_ENABLE=1 python tf_cnn_benchmarks.py --num_gpus=2 --batch_size=128 --model=resnet50 --use_fp16=1
Step	Img/sec	total_loss
1	images/sec: 782.9 +/- 0.0 (jitter = 0.0)	7.938
10	images/sec: 780.4 +/- 1.1 (jitter = 1.7)	7.907
20	images/sec: 771.8 +/- 4.5 (jitter = 5.6)	7.875
30	images/sec: 762.4 +/- 7.5 (jitter = 8.1)	7.868
40	images/sec: 762.8 +/- 5.8 (jitter = 7.4)	7.946
50	images/sec: 754.3 +/- 7.4 (jitter = 7.4)	7.793
60	images/sec: 756.8 +/- 6.2 (jitter = 7.1)	7.867
70	images/sec: 756.6 +/- 5.4 (jitter = 8.1)	7.797
80	images/sec: 756.1 +/- 5.0 (jitter = 9.0)	7.810
90	images/sec: 757.1 +/- 4.5 (jitter = 10.9)	7.800
100	images/sec: 752.6 +/- 5.0 (jitter = 10.9)	7.792

**Comment by witeko** [comment] 2019-03-13 23:11
So I upgraded the ROCM from 2.1 to 2.2 on Ubuntu 18.10 (4.18) and now I cant boot... (I can using an older kernel).
So I switched to Ubuntu 18.04 (4.15) and ROCM 2.2 and it runs but the scaling of multi gpus (radeon 7) is poor.

TF_ROCM_FUSION_ENABLE=1 python tf_cnn_benchmarks.py --num_gpus=2 --batch_size=128 --model=resnet50 --use_fp16
Step	Img/sec	total_loss
1	images/sec: 633.6 +/- 0.0 (jitter = 0.0)	7.928
10	images/sec: 617.7 +/- 25.0 (jitter = 16.2)	7.902
20	images/sec: 628.5 +/- 14.4 (jitter = 14.7)	7.871
30	images/sec: 627.0 +/- 11.3 (jitter = 19.3)	7.867
40	images/sec: 616.1 +/- 11.4 (jitter = 23.7)	7.949
50	images/sec: 607.7 +/- 11.1 (jitter = 28.0)	7.791
60	images/sec: 606.4 +/- 10.1 (jitter = 28.5)	7.875
70	images/sec: 602.6 +/- 9.5 (jitter = 29.2)	7.810
80	images/sec: 595.3 +/- 9.3 (jitter = 30.4)	7.802
90	images/sec: 595.2 +/- 8.4 (jitter = 39.2)	7.817
100	images/sec: 594.6 +/- 8.0 (jitter = 36.1)	7.798

TF_ROCM_FUSION_ENABLE=1 python tf_cnn_benchmarks.py --num_gpus=1 --batch_size=128 --model=resnet50 --use_fp16
Step	Img/sec	total_loss
1	images/sec: 404.8 +/- 0.0 (jitter = 0.0)	7.873
10	images/sec: 405.5 +/- 0.2 (jitter = 0.8)	7.956
20	images/sec: 404.6 +/- 0.3 (jitter = 1.1)	7.959
30	images/sec: 403.0 +/- 0.5 (jitter = 2.5)	7.936
40	images/sec: 401.3 +/- 0.6 (jitter = 5.2)	7.954
50	images/sec: 399.8 +/- 0.7 (jitter = 6.1)	7.711
60	images/sec: 398.3 +/- 0.7 (jitter = 6.8)	7.913
70	images/sec: 396.9 +/- 0.7 (jitter = 8.2)	7.829
80	images/sec: 395.7 +/- 0.7 (jitter = 8.0)	7.982
90	images/sec: 394.5 +/- 0.7 (jitter = 8.9)	7.792
100	images/sec: 393.2 +/- 0.8 (jitter = 8.6)	7.779

**Comment by sunway513** [comment] 2019-03-13 23:16
Hi @witeko , I'll try to repro your issue locally and get back to you.
Just a heads up, I don't think Ubuntu18.10 is in ROCm official support list:
https://github.com/RadeonOpenCompute/ROCm#supported-operating-systems---new-operating-systems-available

**Comment by sunway513** [comment] 2019-03-13 23:57
@witeko , could you post your numbers using CPU as the Parameter Server:
`
TF_ROCM_FUSION_ENABLE=1 python3 tf_cnn_benchmarks.py --num_gpus=2 --batch_size=128 --model=resnet50 --use_fp16 --variable_update=parameter_server --local_parameter_device=cpu
`

**Comment by witeko** [comment] 2019-03-14 00:14
@sunway513 the new number dont look that bad :) TY :)

TF_ROCM_FUSION_ENABLE=1 python tf_cnn_benchmarks.py --num_gpus=2 --batch_size=128 --model=resnet50 --use_fp16 --variable_update=parameter_server --local_parameter_device=cpu
Step	Img/sec	total_loss
1	images/sec: 754.6 +/- 0.0 (jitter = 0.0)	7.934
10	images/sec: 752.0 +/- 0.7 (jitter = 1.3)	7.904
20	images/sec: 751.9 +/- 0.4 (jitter = 1.7)	7.879
30	images/sec: 752.0 +/- 0.4 (jitter = 1.9)	7.871
40	images/sec: 751.3 +/- 0.5 (jitter = 2.0)	7.945
50	images/sec: 751.1 +/- 0.4 (jitter = 2.2)	7.793
60	images/sec: 751.1 +/- 0.4 (jitter = 2.1)	7.869
70	images/sec: 750.9 +/- 0.3 (jitter = 2.1)	7.808
80	images/sec: 750.9 +/- 0.3 (jitter = 2.0)	7.810
90	images/sec: 750.8 +/- 0.3 (jitter = 2.2)	7.813
100	images/sec: 750.8 +/- 0.3 (jitter = 2.2)	7.787

**Comment by sunway513** [comment] 2019-03-14 00:30
Thanks @witeko , for mGPU setup we recommend using CPU as the parameter server, with that we can mostly achieve the best scalability and absolute performance.

**Comment by sunway513** [comment] 2019-03-14 00:57
I'm not able to reproduce any performance regression on my local mGPU setup, hence closing the ticket now. 
@witeko please let me know if you have concerns using the approach that uses CPU as the parameter server.

**Closed by sunway513** 2019-03-14 00:57 UTC
