### ISSUE TITLE
swig with libhsa-runtime64.so.1 failed, reporting can not find libhsa-runtime64.so.1.

### ISSUE THREAD

**Issue by wormwang** [ROCmSoftwarePlatform/tensorflow-upstream#124] opened 2018-08-16 16:56 UTC
### System information
**OS Platform and Distribution: Ubuntu 16.04
**Python version: 2.7 & 3.5
**Bazel version (if compiling from source): 0.15.2
**GCC/Compiler version (if compiling from source):5.4
CUDA/cuDNN version: null
HCC version:1.2.18312
HIPCC version: HIP version: 1.5.18081
GPU model and memory: gfx803,gfx900
HIP_PLATFORM=hcc
bazelrc file:
build --action_env=HIP_PLATFORM=hcc --action_env=HCC_AMDGPU_TARGET=gfx900 --action_env=HIP_PATH=/opt/rocm/hip --action_env=HIPCC_PATH=/opt/rocm/hip/bin --action_env=HSA_PATH=/opt/hsa-rocr-dev/hsa --action_env=HCC_HOME=/opt/rocm/hcc --action_env=ROCM_PATH=/opt/rocm --action_env=HSA_LIBRARY=/opt/hsa-rocr-dev/lib/libhsa-runtime64.so --action_env=HSA_HEADER=/opt/hsa-rocr-dev/include --action_env="LD_LIBRARY_PATH=.:/opt/hsa-rocr-dev/hsa/lib:${LD_LIBRARY_PATH}

Describe the problem
swig with libhsa-runtime64.so.1 failed, reporting can not find libhsa-runtime64.so.1.
 

### Source code / logs
INFO: From Linking external/protobuf_archive/js_embed [for host]:
HIP_PATH=/opt/rocm/hip
HIP_PLATFORM=hcc
HSA_LIBRARY=/opt/rocm/hip
HSA_PATH=/opt/rocm/hsa
HCC_HOME=/opt/rocm/hcc
HIPLDFLAGS=  -Wl,--rpath=/opt/rocm/hip/lib /opt/rocm/hip/lib/libhip_hcc.so /opt/rocm/hip/lib/libhip_device.a  -hc -std=c++amp -L/opt/rocm/hcc/lib -Wl,--rpath=/opt/rocm/hcc/lib -ldl -lm -lpthread -lhc_am -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive -L/opt/rocm/hsa/lib  -l/opt/hsa-rocr-dev/lib/libhsa-runtime64.so -lhc_am -l/opt/rocm/libhsakmt/lib/libhsakmt.so  -lm --amdgpu-target=gfx803 --amdgpu-target=gfx900
hipcc-cmd: /opt/rocm/hcc/bin/hcc   -Wl,--rpath=/opt/rocm/hip/lib /opt/rocm/hip/lib/libhip_hcc.so /opt/rocm/hip/lib/libhip_device.a  -hc -std=c++amp -L/opt/rocm/hcc/lib -Wl,--rpath=/opt/rocm/hcc/lib -ldl -lm -lpthread -lhc_am -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive -L/opt/rocm/hsa/lib  -l/opt/hsa-rocr-dev/lib/libhsa-runtime64.so -lhc_am -l/opt/rocm/libhsakmt/lib/libhsakmt.so  -lm --amdgpu-target=gfx803 --amdgpu-target=gfx900  -o bazel-out/host/bin/external/protobuf_archive/js_embed -Wl,-no-as-needed -B/opt/rocm/hcc/compiler/bin -no-canonical-prefixes -Wl,--build-id=md5 -Wl,--hash-style=gnu -Wl,--gc-sections -Wl,-S -Wl,@bazel-out/host/bin/external/protobuf_archive/js_embed-2.params
ERROR: /data/tensorflow-upstream/tensorflow/contrib/lite/python/interpreter_wrapper/BUILD:22:1: SWIGing tensorflow/contrib/lite/python/interpreter_wrapper/interpreter_wrapper.i failed (Exit 127): swig failed: error executing command 
  (cd /data/.cache/bazel/_bazel_root/83ff65d34212932ecc7e9a2871d57ecd/execroot/org_tensorflow && \
  exec env - \
  bazel-out/host/bin/external/swig/swig -c++ -python -module tensorflow_wrap_interpreter_wrapper -o bazel-out/arm-opt/bin/tensorflow/contrib/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.cc -outdir bazel-out/arm-opt/bin/tensorflow/contrib/lite/python/interpreter_wrapper -Iexternal/eigen_archive -Iexternal/swig -Ibazel-out/arm-opt/genfiles -Ibazel-out/arm-opt/genfiles/external/local_config_python -Iexternal/gemmlowp -Iexternal/com_google_absl -Iexternal/flatbuffers -Iexternal/arm_neon_2_x86_sse -Iexternal/farmhash_archive -Iexternal/swig/Lib -Iexternal/swig/Lib/cffi -Iexternal/swig/Lib/python -Iexternal/swig/Lib/std -Iexternal/swig/Lib/typemaps tensorflow/contrib/lite/python/interpreter_wrapper/interpreter_wrapper.i)
bazel-out/host/bin/external/swig/swig: **error while loading shared libraries: libhsa-runtime64.so.1**: cannot open shared object file: No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 1532.269s, Critical Path: 100.68s
INFO: 1763 processes: 1763 local.
FAILED: Build did NOT complete successfully

**Comment by whchung** [comment] 2018-08-16 17:06
@wormwang to my understanding you build ROCR runtime from source. it can also be shown in your build log:

```
/opt/hsa-rocr-dev/lib/libhsa-runtime64.so
```

you might need to change `/etc/ld.so.conf`, or `/etc/ld.so.conf.d/` to add one file so the directory containing `libhsa-runtime64.so` and `libhsa-runtime64.so.` would be loaded automatically.

on a standard rocm installation on ubuntu, `/etc/ld.conf.d/hsa-rocr-dev.conf` would be added with content:

```
/opt/rocm/hsa/lib
```

**Comment by whchung** [comment] 2018-08-16 17:07
since the issue is not related to tensorflow rocm port, but more about your system configuration i'm closing the ticket hereby. feel free to raise new ticket or reopen this one should you feel necessary.

**Closed by whchung** 2018-08-16 17:07 UTC
