### ISSUE TITLE
No device code available for function

### ISSUE THREAD

**Issue by Avatat** [ROCmSoftwarePlatform/tensorflow-upstream#273] opened 2018-12-27 02:05 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.10
- TensorFlow installed from (source or binary): source (tensorflow-upstream-develop-upstream-sync-181224)
- TensorFlow version: 1.12
- Python version: 3.7
- Installed using virtualenv? pip? conda?: -
- Bazel version (if compiling from source): 0.21
- GCC/Compiler version (if compiling from source): HCC clang version 8.0.0, based on HCC 1.3.18482-757fb49-6ec3c61-ab3b88f
- CUDA/cuDNN version: ROCm 2.0
- GPU model and memory: RX 480 8G

**Describe the problem**
After build is completed and pip package installed, I tried to run resnet50 from tf_cnn_benchmarks and I got this error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  No device code available for function: _ZN10tensorflow7functor28FillPhiloxRandomKernelLaunchINS_6random27TruncatedNormalDistributionINS2_19SingleSampleAdapterINS2_12PhiloxRandomEEEfEEEEvS5_PNT_17ResultElementTypeExS8_
Fatal Python error: Aborted
```
Tensorflow 1.12 from pip works correctly, but there is no support for AVX and SSE4.

**Comment by sunway513** [comment] 2018-12-27 19:42
Hi @Avatat , Ubuntu 18.10 is not supported by ROCm yet, please consult with the following doc:
https://github.com/RadeonOpenCompute/ROCm#supported-operating-systems---new-operating-systems-available
It would be helpful if you can change to use a supported OS environment (UB16.04 or UB18.04), if issue remains, please provide the build logs.

**Comment by Avatat** [comment] 2018-12-27 21:36
@sunway513, tensorflow-rocm from pip is either not supported on 18.10, but works like a charm.
I will try on 18.04 and let you know.

**Comment by sunway513** [comment] 2018-12-27 22:14
Thanks @Avatat , to compile TF from source requires more dependencies than installing from pypl, especially you'll have to make sure the ROCm base toolchain (hip/hcc) to be functioning correctly. 
In fact we have a docker image that contains all you need to rebuild TF from source, you can try that as well:
rocm/tensorflow:rocm2.0-tf1.12-python3-dev

**Comment by kinred** [comment] 2019-01-08 14:09
Have the same issue after compiling on Ubuntu 18.04. and upgrading DKMS through package manager to ROCm 2.0. 

Compiling the same source with ROCm 1.9.2 worked fine. 

Same specs as in original report beside using a Vega FE.

The pip tensorflow_rocm package and the Docker image doe work with ROCm 2.0 but have about 15% less performance on CNN models (like ResNet-50) compared to a working build with ROCm 1.9.2

**Comment by sunway513** [comment] 2019-01-15 22:20
Hi @kinred , there's a known issue in ROCm2.0 impacts the performance, that'll be fixed in ROCm2.1. 
In ROCm2.0, you can try the following commands:
```
sudo sh -c 'echo "options amdgpu noretry=1" >> /etc/modprobe.d/amdgpu.conf'
sudo update-initramfs -u
sudo reboot
```
Please open a new ticket for the performance issue if the above workaround can not fix it.

**Closed by sunway513** 2019-01-15 22:20 UTC

**Comment by kinred** [comment] 2019-01-17 10:16
@sunway513 thanks, the above module config option improves the performance about 10%, still 5% missing to the same performance as with a ROCM1.9.2 based build, probably related to not able to use an optimized compiler settings for the CPU code.

The issue with an dedicated Tensorflow build using ROCm 2.0 (retested with current git master) is still crashing  with the error as described in the original issue:

```
190] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15306 MB memory) -> physical GPU (device: 0, name: Vega 10 XTX [Radeon Vega Frontier Edition], pci bus id: 0000:0c:00.0)
terminate called after throwing an instance of 'std::runtime_error'
  what():  No device code available for function: _ZN10tensorflow7functor28FillPhiloxRandomKernelLaunchINS_6random19UniformDistributionINS2_12PhiloxRandomEfEEEEvS4_PNT_17ResultElementTypeExS6_
Fatal Python error: Aborted
```

**Comment by sunway513** [comment] 2019-01-17 15:44
Hi @kinred , could you try to rebuild from source using the docker image `rocm/tensorflow:rocm2.0-tf1.12-python3-dev' ? The error message indicates there's no GPU code available from the built TF whl package, this should be caused by the user bit package configuration issues.
