### ISSUE TITLE
GAN training causes GPU hang after a few seconds

### ISSUE THREAD

**Issue by liamnr** [ROCmSoftwarePlatform/tensorflow-upstream#282] opened 2019-01-08 01:17 UTC
When trying to train a GAN using the following Tensorflow implementation of SAGAN:
https://github.com/taki0112/Self-Attention-GAN-Tensorflow

the system locks up every time after the script has run for a few seconds.

To reproduce:
python3 download.py celebA
python3 main.py --phase train --dataset celebA --gan_type hinge --batch_size=1 --img_size=128

GPU: Radeon RX 470 8GB

[tf_env.txt](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/2734853/tf_env.txt)
[stderr.txt](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/2734851/stderr.txt)
[kernel.log](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/2734852/kernel.log)

**Comment by sunway513** [comment] 2019-01-08 01:45
Hi @liamnr , the failure was a VMEM fault, it should be related to your local ROCm configuration.
Can you try to run HIP unit test and provide the results here?
https://github.com/ROCm-Developer-Tools/HIP/blob/roc-2.0.x/tests/README.md

**Comment by liamnr** [comment] 2019-01-08 02:43
I ran the tests and they completed successfully:
100% tests passed, 0 tests failed out of 119

Full output:
[hip_tests.log](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/2734968/hip_tests.log)

I also tried a few different things before this, so tensorflow isn't entirely broken for me. For example, Resnet-50 inference with a pre-trained model seemed to work fine.

**Comment by sunway513** [comment] 2019-01-08 03:06
Thanks for confirming! I’ll try to repro the issue on Polaris GPU and let you know.

**Comment by sunway513** [comment] 2019-01-08 16:11
Hi @liamnr , I've tried the sample on several of my dev nodes, can not repro the failure you've mentioned in the logs. 
To help isolate your issue, could you try the following docker image that I used to run the model?
`sunway513/tensorflow:rocm2.0-tf1.12-gan-test`
Besides, the model you referred to is not compatible with the latest `scipy` lib, I can see the following failure message after running for a while:
```Epoch: [ 0] [  498/10000] time: 59.5604, d_loss: 0.00000000, g_loss: 11.39575768
Epoch: [ 0] [  499/10000] time: 59.6686, d_loss: 0.00000000, g_loss: 11.19164658
Traceback (most recent call last):
  File "main.py", line 110, in <module>
    main()
  File "main.py", line 98, in main
    gan.train()
  File "/root/Self-Attention-GAN-Tensorflow/SAGAN.py", line 370, in train
    './' + self.sample_dir + '/' + self.model_name + '_train_{:02d}_{:05d}.png'.format(epoch, idx+1))
  File "/root/Self-Attention-GAN-Tensorflow/utils.py", line 84, in save_images
    return imsave(inverse_transform(images), size, image_path)
  File "/root/Self-Attention-GAN-Tensorflow/utils.py", line 108, in imsave
    return scipy.misc.imsave(path, merge(images, size))
AttributeError: module 'scipy.misc' has no attribute 'imsave'```

**Comment by liamnr** [comment] 2019-01-08 22:23
I tried to run this on the docker image your provided, however it causes a GPU fault at the exact same point of the script.

With some more testing, I noticed that it works for me with --img_size=64, but not 128 or 256.
With --up_sample=false, which causes an upsampling+convolution operation to be replaced by a deconvolution, it also works with 128 and 256. So perhaps there is a problem with tf.image.resize_nearest_neighbor?

Also, I believe the problem with scipy.misc can be resolved by installing the python3-pil package.

**Comment by sunway513** [comment] 2019-01-09 17:13
@liamnr I just got rx480 8G board and now can repro your issue locally with ROCm2.0.
It looks like a regression in ROCm2.0 user level packages, the same set of test (img_size=128) can run correctly in ROCm1.9.2. I'll triage deeper into the issue, in the meanwhile, you can use the following docker image to avoid the issue:
`sunway513/tensorflow:rocm1.9.2-tf1.12-gan-test`

**Comment by sunway513** [comment] 2019-01-30 16:50
@liamnr can you try the following steps? That can help enable the gan model on my Polaris 8GB card:
```
cd ~ && mkdir rocm1.9.2-opencl && cd rocm1.9.2-opencl &&
wget https://www.dropbox.com/s/rtwe1zrpuphbyqm/rocm-opencl-1.2.0-2018111340_amd64.deb && 
wget https://www.dropbox.com/s/6gp2g5zju66i4e9/rocm-opencl-dev-1.2.0-2018111340_amd64.deb && 
sudo dpkg -i rocm-opencl*.deb && rm -rf ~/.cache
```

**Comment by sunway513** [comment] 2019-02-07 19:26
@liamnr any feedback for the workaround steps?

**Comment by liamnr** [comment] 2019-03-11 21:11
Sorry for the late response.
Yes, with this the SAGAN and BigGAN models work without any problems using ROCM 2.1 and Tensorflow 1.13.

**Comment by sunway513** [comment] 2019-06-08 05:33
Hi @liamnr , the issue has been fixed in ROCm2.5 release, please kindly try it out and let us know. Docker image:
rocm/tensorflow:rocm2.5-tf1.13-python3

**Closed** 2019-06-09 04:36 UTC
Labels: bug, gfx803
