### ISSUE TITLE
tensorflow-rocm ihipException when not having access to Driver/GPU

### ISSUE THREAD

**Issue by robzor92** [ROCmSoftwarePlatform/tensorflow-upstream#360] opened 2019-03-18 12:56 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary PyPi
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- ROCm/MIOpen version: 2.2.31
- GPU model and memory: Vega vii 16GB

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
Using tensorflow-rocm throws ihipException and terminates training when Driver/GPU fails to load. This may happen when a process is not allowed to access to GPUs /kfd due to device access constraints in Cgroup for example.

**Describe the expected behavior**
Throw an error and fall back to using CPU only.  This is the behaviour in tensorflow-gpu (https://github.com/tensorflow/tensorflow/blob/e9678fd3b86ad67d947c21a3845790875a9d903d/tensorflow/stream_executor/cuda/cuda_driver.cc#L307) and the behaviour I would expect tensorflow-rocm to also exhibit. 

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
    import tensorflow as tf
    import numpy as np
    import os

    from tensorflow.examples.tutorials.mnist import input_data
    mnist = input_data.read_data_sets('MNIST_data')

    def input(dataset):
        return dataset.images, dataset.labels.astype(np.int32)

    # Specify feature
    feature_columns = [tf.feature_column.numeric_column("x", shape=[28, 28])]

    # Build 2 layer DNN classifier
    classifier = tf.estimator.DNNClassifier(
    feature_columns=feature_columns,
    hidden_units=[256, 32],
    optimizer=tf.train.AdamOptimizer(1e-4),
    n_classes=10,
    dropout=0.1,
    model_dir=os.getcwd()
    )

    # Define the training inputs
    train_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": input(mnist.train)[0]},
    y=input(mnist.train)[1],
    num_epochs=None,
    batch_size=32,
    shuffle=True
    )

    classifier.train(input_fn=train_input_fn, steps=300)

    # Define the test inputs
    test_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": input(mnist.test)[0]},
    y=input(mnist.test)[1],
    num_epochs=1,
    shuffle=False
    )

    # Evaluate accuracy
    accuracy_score = classifier.evaluate(input_fn=test_input_fn)["accuracy"]
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

terminate called after throwing an instance of 'ihipException'
 what():  std::exception
TensorBoard caught SIGTERM; exiting...

**Comment by sunway513** [comment] 2019-03-18 14:40
Hi @robzor92 , we have the similar fallback mechanisms in tensorflow-rocm stack. If you'd like to fall back to CPU path, please use the following environment variable:
`export HIP_VISIBLE_DEVICES=-1`
If HIP runtime can see the GPUs available from the system, it'll try to initialize the GPU context; however, when the GPUs resources are not available due to cgroup limitations, then you'll see the ihipException error and HIP runtime would abort immediately.

**Comment by sunway513** [comment] 2019-03-18 16:13
Hi @robzor92 , I can reproduce the error you've reported on this issue now, by launching docker images without `--device=/dev/dri` interfaces passing to `docker run`. I can see the "std::exception" error with `HIP_VISIBLE_DEVICES` been set to `-1`. 
Let me triage the issue with HIP runtime, will update.

**Comment by robzor92** [comment] 2019-03-18 16:16
Thanks for the response @sunway513. I tried the environment variable and it does indeed work in the "normal" use-case. So basically when I have access to /dev/kfd, /dev/card1 and dev/renderD129. 

However if I deny access to the GPU, i.e remove /dev/card1 and /dev/renderD129 from devices that can be accessed in Cgroups. It throws ihipException even though I exported the environment variable. In that setup I only have access to the kernel fusion driver. So I'm guessing HIP_VISIBLE_DEVICES is not taken into account at that stage, so the ihipException is being throw before it is even read.

**Comment by sunway513** [comment] 2019-03-18 18:25
Hi @robzor92 , I have done some preliminary triaging of the issue. By removing this [line](https://github.com/ROCm-Developer-Tools/HIP/blob/0c4a40efcc974e5a4b2935fb84b3e8d368e9880b/src/hip_hcc.cpp#L1406-L1409) in HIP runtime that aborts the process when CPU HSA agent not found, I can see tf-rocm fails back to the CPU path correctly. 
Here's my logs:
```
2019-03-18 18:14:39.448555: E tensorflow/stream_executor/rocm/rocm_driver.cc:965] could not retrieve ROCM device count: HIP_ERROR_NoDevice
2019-03-18 18:14:47.193415: step 0, duration = 0.686
2019-03-18 18:14:54.139972: step 10, duration = 0.681
```
That would require both /dev/kfd and /dev/dri to be invisible to ROCm stack, here's the steps to try that using [docker image](https://cloud.docker.com/u/rocm/repository/docker/rocm/tensorflow) (so it won't break your local configurations):
```
sudo docker run -it rocm/tensorflow:latest

cd ~ && wget https://www.dropbox.com/s/xfxn97np56ftwrt/rocm2.2-hip-fix.tar && tar -xvf rocm2.2-hip-fix.tar && cd rocm2.2-hip-fix/ && dpkg -i *.deb 
cd ~/models/tutorials/image/alexnet/
python3 alexnet_benchmark.py 
```
Does this meet your expectations? Please let me know your feedback so we can decide what to recommend to the HIP team.

**Comment by robzor92** [comment] 2019-03-18 18:59
@sunway513 That's great news! Hopefully I will be able to provide you with feedback tomorrow. This also means there is no need to export `HIP_VISIBLE_DEVICES` for CPU fallback to happen? (provided /dev/kfd and /dev/dri/* is not visible).

**Comment by sunway513** [comment] 2019-03-18 19:11
@robzor92 That's correct, the modified logic takes precedence over `HIP_VISIBLE_DEVICES`, so you don't need to set environment variables for the above experiment.

**Comment by robzor92** [comment] 2019-03-19 18:52
@sunway513 I tried out the docker example you provided and using the hip fix in our system. Both work fine and as I would expect. For my use-case this fallback mechanism will do. For other users it might be that they have access to /dev/kfd but not /dev/dri/*, will the fallback work for them too? At any rate my issue have been resolved now. Thanks a lot for the help!

**Comment by sunway513** [comment] 2019-03-20 01:27
Thanks @robzor92 for confirming it! We'll work with HIP team for the enhancement, and will update you the target release when available.

To the other question, if the system has access to /dev/kfd but not /dev/dri/* interfaces, this fallback path won't work correctly.
In that case, HCC runtime libraries and the other ROCm components will be able to detect the existence of amdgpu driver, therefore would try to initialize the GPU context and then result in failure.

**Comment by robzor92** [comment] 2019-05-07 15:27
Hello @sunway513! Have you guys made any progress on this issue?

**Comment by mangupta** [comment] 2019-05-08 04:24
@sunway513 @robzor92 I believe https://github.com/ROCm-Developer-Tools/HIP/pull/1064 which has been merged addresses this.

**Comment by robzor92** [comment] 2019-05-08 08:17
@sunway513 @mangupta Thanks for that! I see ROCm 2.5 is the target release.

**Comment by sunway513** [comment] 2019-06-14 15:22
Hi @robzor92 , would you try ROCm2.5 and see if the HIP issue is fixed there?

**Comment by robzor92** [comment] 2019-06-18 07:43
@sunway513 I have not been able to try it on a system with an AMD GPU yet, I did try it on a system where I don't have one and installed the ROCm-stack and the fallback works correctly there. So we can close it for now, and I can reopen it if I find any problems once I am able to try it in a real setup. I have some other tasks that takes priority right now.

**Comment by sunway513** [comment] 2019-06-18 13:22
@robzor92 sounds good, please let us know if there's anything else we can help with :-)

**Closed by sunway513** 2019-06-18 13:22 UTC

**Comment by robzor92** [comment] 2019-07-25 12:48
@sunway513 I tried it now with ROCm 2.6 and tensorflow-rocm 1.14 and the fallback works correctly.

**Comment by sunway513** [comment] 2019-07-25 14:42
Thank you @robzor92 to confirm the fix :-)
