### ISSUE TITLE
Error with MirroredStrategy

### ISSUE THREAD

**Issue by mnvmld** [ROCmSoftwarePlatform/tensorflow-upstream#285] opened 2019-01-14 11:39 UTC
Hello! Please help! 
I have problem with using Mirrored Strategy on tensorflow-rocm. When I try use it I get next error:
```
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpszzzlis4
INFO:tensorflow:Using config: {'_save_checkpoints_steps': None, '_device_fn': None, '_is_chief': True, '_train_distribute': <tensorflow.contrib.distribute.python.mirrored_strategy.MirroredStrategy object at 0x7ff9da20a470>, '_save_checkpoints_secs': 600, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': '/tmp/tmpszzzlis4', '_num_ps_replicas': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7ff9da20a3c8>, '_tf_random_seed': None, '_session_config': None, '_global_id_in_cluster': 0, '_keep_checkpoint_max': 5, '_evaluation_master': '', '_service': None, '_task_type': 'worker', '_master': '', '_num_worker_replicas': 1, '_save_summary_steps': 100, '_log_step_count_steps': 100, '_task_id': 0}
INFO:tensorflow:Device is available but not used by distribute strategy: /device:CPU:0
INFO:tensorflow:Device is available but not used by distribute strategy: /device:XLA_CPU:0
INFO:tensorflow:Configured nccl all-reduce.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:batch_all_reduce invoked for batches size = 2 with algorithm = nccl and num_packs = 1
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
~/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1321     try:
-> 1322       return fn(*args)
   1323     except errors.OpError as e:

~/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1304       # Ensure any changes to the graph are reflected in the runtime.
-> 1305       self._extend_graph()
   1306       return self._call_tf_sessionrun(

~/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/client/session.py in _extend_graph(self)
   1339       with self._graph._lock:  # pylint: disable=protected-access
-> 1340         tf_session.ExtendSession(self._session)
   1341     else:

InvalidArgumentError: No OpKernel was registered to support Op 'NcclAllReduce' with these attrs.  Registered devices: [CPU,GPU,XLA_CPU], Registered kernels:
  <no registered kernels>

	 [[Node: NcclAllReduce_1 = NcclAllReduce[T=DT_FLOAT, num_devices=2, reduction="sum", shared_name="c0", _device="/device:GPU:1"](split_1)]]
```

But before It I had 
```
2019-01-14 13:32:47.678855: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1562] Adding visible gpu devices: 0, 1
2019-01-14 13:32:47.681763: I tensorflow/core/common_runtime/gpu/gpu_device.cc:989] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-01-14 13:32:47.681978: I tensorflow/core/common_runtime/gpu/gpu_device.cc:995]      0 1 
2019-01-14 13:32:47.682131: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1008] 0:   N N 
2019-01-14 13:32:47.682457: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1008] 1:   N N 
2019-01-14 13:32:47.682841: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1124] Created TensorFlow device (/device:GPU:0 with 3540 MB memory) -> physical GPU (device: 0, name: Ellesmere [Radeon RX 470/480], pci bus id: 0000:01:00.0)
2019-01-14 13:32:47.683324: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1124] Created TensorFlow device (/device:GPU:1 with 3540 MB memory) -> physical GPU (device: 1, name: Ellesmere [Radeon RX 470/480], pci bus id: 0000:02:00.0)
2019-01-14 13:32:48.417036: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1562] Adding visible gpu devices: 0, 1
2019-01-14 13:32:48.417420: I tensorflow/core/common_runtime/gpu/gpu_device.cc:989] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-01-14 13:32:48.417511: I tensorflow/core/common_runtime/gpu/gpu_device.cc:995]      0 1 
2019-01-14 13:32:48.417561: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1008] 0:   N N 
2019-01-14 13:32:48.417589: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1008] 1:   N N 
2019-01-14 13:32:48.417691: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1124] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3540 MB memory) -> physical GPU (device: 0, name: Ellesmere [Radeon RX 470/480], pci bus id: 0000:01:00.0)
2019-01-14 13:32:48.417891: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1124] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 3540 MB memory) -> physical GPU (device: 1, name: Ellesmere [Radeon RX 470/480], pci bus id: 0000:02:00.0)
```

Early I have same error when I try use Conv2, but now this error fixed. May be purge mivisionx helped, I don't know.

```
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

```
sudo dpkg -l | grep linux-headers | grep ii | awk '{print $3}'
4.15.0-29.31
4.15.0-29.31
4.15.0-43.46
4.15.0-43.46
4.18.0-13.14~18.04.1
4.18.0-13.14~18.04.1
4.20.0-rc6-18.12.13.amdgpu.ubuntu-3
4.15.0.43.45
```

```
dmesg | grep kfd
[    2.530090] kfd kfd: Allocated 3969056 bytes on gart
[    2.530200] kfd kfd: added device 1002:67df
[    3.728838] kfd kfd: Allocated 3969056 bytes on gart
[    3.729021] kfd kfd: added device 1002:67df
```

```
dmesg | grep amd
[    0.000000] Linux version 4.20.0-rc6-18.12.13.amdgpu.ubuntu (martin@Main-PC) (gcc version 8.2.0 (Ubuntu 8.2.0-7ubuntu1)) #3 SMP Thu Dec 13 08:21:34 CET 2018 ()
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-4.20.0-rc6-18.12.13.amdgpu.ubuntu root=UUID=de3fa24f-c974-4d46-8e3e-2fd1b16c8037 ro quiet splash vt.handoff=1
[    0.032478] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.20.0-rc6-18.12.13.amdgpu.ubuntu root=UUID=de3fa24f-c974-4d46-8e3e-2fd1b16c8037 ro quiet splash vt.handoff=1
[    1.007090] usb usb1: Manufacturer: Linux 4.20.0-rc6-18.12.13.amdgpu.ubuntu xhci-hcd
[    1.009076] usb usb2: Manufacturer: Linux 4.20.0-rc6-18.12.13.amdgpu.ubuntu xhci-hcd
[    1.065442] usb usb3: Manufacturer: Linux 4.20.0-rc6-18.12.13.amdgpu.ubuntu xhci-hcd
[    1.065735] usb usb4: Manufacturer: Linux 4.20.0-rc6-18.12.13.amdgpu.ubuntu xhci-hcd
[    1.067414] pcie_mp2_amd: AMD(R) PCI-E MP2 Communication Driver Version: 1.0
[    1.338311] [drm] amdgpu kernel modesetting enabled.
[    1.338564] amdgpu 0000:01:00.0: enabling device (0000 -> 0003)
[    1.340251] amdgpu 0000:01:00.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=none:owns=none
[    2.341698] amdgpu 0000:01:00.0: VRAM: 4096M 0x000000F400000000 - 0x000000F4FFFFFFFF (4096M used)
[    2.341699] amdgpu 0000:01:00.0: GART: 256M 0x000000FF00000000 - 0x000000FF0FFFFFFF
[    2.341790] [drm] amdgpu: 4096M of VRAM memory ready
[    2.341791] [drm] amdgpu: 2860M of GTT memory ready.
[    2.533827] [drm] Initialized amdgpu 3.27.0 20150101 for 0000:01:00.0 on minor 1
[    2.533887] amdgpu 0000:02:00.0: enabling device (0000 -> 0003)
[    3.537911] amdgpu 0000:02:00.0: VRAM: 4096M 0x000000F400000000 - 0x000000F4FFFFFFFF (4096M used)
[    3.537913] amdgpu 0000:02:00.0: GART: 256M 0x000000FF00000000 - 0x000000FF0FFFFFFF
[    3.539349] [drm] amdgpu: 4096M of VRAM memory ready
[    3.539351] [drm] amdgpu: 2860M of GTT memory ready.
[    3.732449] [drm] Initialized amdgpu 3.27.0 20150101 for 0000:02:00.0 on minor 2
```

Thanks

**Comment by jeffdaily** [comment] 2019-01-14 15:41
The problem is the following line:
`InvalidArgumentError: No OpKernel was registered to support Op 'NcclAllReduce' with these attrs.  Registered devices: [CPU,GPU,XLA_CPU], Registered kernels:`

It seems the import for nccl ops is taking place instead of our rccl ops.  Which version of tensorflow are you using so we can address this?

**Comment by jeffdaily** [comment] 2019-01-14 16:04
Hi @mnvmld.  Possibly related to your issue, I submitted a PR (https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/286) against our develop-upstream branch.  Please let us know which version of TF you are using.  For example, if you're building from source which branch you're using.  Or if you're using a docker container.  Or if you're using a wheel.  Thanks.

**Comment by mnvmld** [comment] 2019-01-15 13:59
Hi @jeffdaily ! 
I install tensorflow using: `pip install tensorflow-rocm` new version.
I understand that problem in that line. I don't understand why <no registered kernels>.
Same problem was when I try use Conv2, but now using Conv2 don't get this error.

**Comment by sunway513** [comment] 2019-02-07 19:25
@mnvmld  if you install from pypl, you'll go for the latest TF public release, at the time being, it's r1.12-rocm. 
It looks like your issue might be resolved in our development branch. 
Can you try to rebuild tensorflow using the develop-upstream branch? Instructions are here:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-build-from-source.md
I'll close the ticket, for now, feel free to reopen it if you still see issues there.

**Closed by sunway513** 2019-02-07 19:25 UTC

**Comment by mnvmld** [comment] 2019-02-08 04:34
> @mnvmld if you install from pypl, you'll go for the latest TF public release, at the time being, it's r1.12-rocm.
> It looks like your issue might be resolved in our development branch.
> Can you try to rebuild tensorflow using the develop-upstream branch? Instructions are here:
> https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-build-from-source.md
> I'll close the ticket, for now, feel free to reopen it if you still see issues there.

Thanks. I reinstalled tensorflow-rocm from githab. Pypl gave me only version 0.8... Now I have v1.12. Problem is resolved.
