### ISSUE TITLE
Convergence issue with Keras on ROCm

### ISSUE THREAD

**Issue by mikelynch** [ROCmSoftwarePlatform/tensorflow-upstream#251] opened 2018-11-23 19:57 UTC
I discovered this issue when trying to use Keras with `tensorflow-rocm`. As the same script works as expected on CPU, I think this is an issue with `tensorflow-rocm`. This is the simplest example I've found that demonstrates it – there are two models, one which is okay, and one with an extra `MaxPooling2D` layer which fails under Keras on ROCm.

**System information**
- Custom code: https://gist.github.com/mikelynch/3ce6b6fce1a0045bad8c904bf2351de8
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from binary
- TensorFlow version: `v1.12.0-871-gf480b4a 1.12.0`
- Python version: `Python 3.6.7`
- ROCm version: `rocm-dkms`, `rocm-libs` are 1.9.307
- GPU model and memory: AMD Radeon Pro Duo Polaris (reported as two WX 7100)

**Describe the current behavior**
The demo code trains two similar models twice, once using `optimizer=tf.train.AdamOptimizer()` and once using `optimizer=keras.optimizers.Adam()`. Currently using `tensorflow-rocm`, the first model gets very similar results for both optimizers, but for the second model, with the Keras optimizer the accuracy briefly increases before dramatically falling, even though using `tf.train.AdamOptimizer` works fine.

When training on CPU, the both optimizers give the same results.

**Describe the expected behavior**
The GPU results should be comparable to CPU (i.e. Keras optimizers should work fine in all cases).

**Code to reproduce the issue**
See gist above.

**Other info / logs**
GPU training log: https://gist.github.com/mikelynch/8d6c4d98519a1033d01ca15cfc266814
CPU training log: https://gist.github.com/mikelynch/76bd1af6a6ea4e71c7aed801d500b1fc

Comparison:

Model | Optimizer | Device | Train accuracy
----- | --------- | ------ | --------------
1     | Keras     | GPU    | 0.9685        
1     | Keras     | CPU    | 0.9704        
1     | TF        | GPU    | 0.9703        
1     | TF        | CPU    | 0.9706        
2     | Keras     | GPU    | **0.3007**    
2     | Keras     | CPU    | 0.9682        
2     | TF        | GPU    | 0.9677        
2     | TF        | CPU    | 0.9696

**Comment by mikelynch** [comment] 2018-11-23 22:35
I've just tested the same script with an EC2 nVidia GPU instance, and get equivalent results to the CPU ones from earlier: https://gist.github.com/mikelynch/fdb30d1da1befcbcccf12298e9fbd6b4

**Comment by briansp2020** [comment] 2018-11-24 19:05
Tried it at GPUeater.com using Vega FE and it was fine. However, RX580 seems to have issues.

When using TF 1.10, I got below result.

> Using TensorFlow backend.
> model1:
> optimizer={<keras.optimizers.Adam object at 0x7fea896b6940>}
> Train on 60000 samples, validate on 10000 samples
> Epoch 1/1
> 2018-11-24 18:48:51.956591: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1519] Found device 0 with properties: 
> name: Device 67df
> AMDGPU ISA: gfx803
> memoryClockRate (GHz) 1.35
> pciBusID 0000:01:00.0
> Total memory: 8.00GiB
> Free memory: 7.75GiB
> 2018-11-24 18:48:51.956623: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1630] Adding visible gpu devices: 0
> 2018-11-24 18:48:51.956655: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1039] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2018-11-24 18:48:51.956663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045]      0 
> 2018-11-24 18:48:51.956683: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1058] 0:   N 
> 2018-11-24 18:48:51.956740: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7539 MB memory) -> physical GPU (device: 0, name: Device 67df, pci bus id: 0000:01:00.0)
> 2018-11-24 18:49:00.585954: I tensorflow/core/kernels/conv_grad_input_ops.cc:1021] running auto-tune for Backward-Data
> 2018-11-24 18:49:01.649626: I tensorflow/core/kernels/conv_grad_filter_ops.cc:974] running auto-tune for Backward-Filter
> 2018-11-24 18:49:03.366466: I tensorflow/core/kernels/conv_grad_filter_ops.cc:974] running auto-tune for Backward-Filter
> 60000/60000 [==============================] - 34s 562us/step - loss: 0.0972 - acc: 0.9701 - val_loss: 0.0567 - val_acc: 0.9823
> 
> optimizer={<tensorflow.python.training.adam.AdamOptimizer object at 0x7fea8007c9e8>}
> Train on 60000 samples, validate on 10000 samples
> Epoch 1/1
> 60000/60000 [==============================] - 15s 255us/step - loss: 0.0983 - acc: 0.9695 - val_loss: 0.0326 - val_acc: 0.9892
> 
> model2:
> optimizer={<keras.optimizers.Adam object at 0x7fea88031d30>}
> Train on 60000 samples, validate on 10000 samples
> Epoch 1/1
> 60000/60000 [==============================] - 13s 209us/step - **loss: 0.1451** - acc: 0.9576 - val_loss: 0.0590 - val_acc: 0.9832
> 
> optimizer={<tensorflow.python.training.adam.AdamOptimizer object at 0x7fea83d2f588>}
> Train on 60000 samples, validate on 10000 samples
> Epoch 1/1
> 60000/60000 [==============================] - 11s 181us/step - **loss: 13.0587** - acc: 0.1777 - val_loss: 14.2887 - val_acc: 0.1135

The result shows bad accuracy when using tf optimizer. Even when using Keras optimizer, loss seems higher than it should be.

When I upgraded TF to 1.12, I got the same behavior as the OP.

> Using TensorFlow backend.
> WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/distributions/distribution.py:265: ReparameterizationType.__init__ (from tensorflow.python.ops.distributions.distribution) is deprecated and will be removed after 2019-01-01.
> Instructions for updating:
> The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
> WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/distributions/bernoulli.py:169: RegisterKL.__init__ (from tensorflow.python.ops.distributions.kullback_leibler) is deprecated and will be removed after 2019-01-01.
> Instructions for updating:
> The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
> model1:
> optimizer={<keras.optimizers.Adam object at 0x7efc503a4f60>}
> Train on 60000 samples, validate on 10000 samples
> Epoch 1/1
> 2018-11-24 19:00:45.197927: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
> 2018-11-24 19:00:45.200661: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1530] Found device 0 with properties: 
> name: Device 67df
> AMDGPU ISA: gfx803
> memoryClockRate (GHz) 1.35
> pciBusID 0000:01:00.0
> Total memory: 8.00GiB
> Free memory: 7.75GiB
> 2018-11-24 19:00:45.200693: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Adding visible gpu devices: 0
> 2018-11-24 19:00:45.200751: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1051] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2018-11-24 19:00:45.200761: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1057]      0 
> 2018-11-24 19:00:45.200926: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1070] 0:   N 
> 2018-11-24 19:00:45.201084: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1189] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7539 MB memory) -> physical GPU (device: 0, name: Device 67df, pci bus id: 0000:01:00.0)
> 2018-11-24 19:00:52.389337: I tensorflow/core/kernels/conv_grad_input_ops.cc:1023] running auto-tune for Backward-Data
> 2018-11-24 19:00:53.123016: I tensorflow/core/kernels/conv_grad_filter_ops.cc:975] running auto-tune for Backward-Filter
> 2018-11-24 19:00:54.446212: I tensorflow/core/kernels/conv_grad_filter_ops.cc:975] running auto-tune for Backward-Filter
> 60000/60000 [==============================] - 31s 522us/step - loss: 0.0988 - acc: 0.9697 - val_loss: 0.0434 - val_acc: 0.9863
> 
> optimizer={<tensorflow.python.training.adam.AdamOptimizer object at 0x7efc4c30d908>}
> Train on 60000 samples, validate on 10000 samples
> Epoch 1/1
> 60000/60000 [==============================] - 16s 266us/step - loss: 0.0984 - acc: 0.9700 - val_loss: 0.0380 - val_acc: 0.9872
> 
> model2:
> optimizer={<keras.optimizers.Adam object at 0x7efc4c133278>}
> Train on 60000 samples, validate on 10000 samples
> Epoch 1/1
> 60000/60000 [==============================] - 13s 211us/step - **loss: 12.1168** - acc: 0.2337 - val_loss: 14.5740 - val_acc: 0.0958
>
>optimizer={<tensorflow.python.training.adam.AdamOptimizer object at 0x7efc44835898>}
>Train on 60000 samples, validate on 10000 samples
>Epoch 1/1
>60000/60000 [==============================] - 11s 179us/step - loss: 0.1006 - acc: 0.9690 - val_loss: 0.0397 - val_acc: 0.9884

**Comment by pricebenjamin** [comment] 2018-11-26 04:45
> Tried it at GPUeater.com using Vega FE and it was fine. However, RX580 seems to have issues.

Doubly confirmed: no apparent issue on Vega FE, but loss explodes on RX 580.

> The result shows bad accuracy when using tf optimizer. Even when using Keras optimizer, loss seems higher than it should be.

If you continue training with `get_model2`  (e.g. for 10 epochs), both optimizers fail.

`get_model1` appears to be stable, even up to 30 epochs, but results show consistently higher loss compared to Vega FE.

**Comment by Bengt** [comment] 2019-05-14 11:25
I backported the test to python 3.5 for easier reproduction:

<https://gist.github.com/Bengt/3042bafe5e197463c396d1c032017eff>

I am reproducing using ROCm 2.1 and Tensorflow 1.12:

```
$ docker run -it --device=/dev/kfd --device=/dev/dri --group-add video rocm/tensorflow:rocm2.1-tf1.12-python3
$ python3 -m pip install keras
$ wget https://gist.githubusercontent.com/Bengt/3042bafe5e197463c396d1c032017eff/raw/ea0d8b3fa6e514c384f18f04ad390532931ce628/tf_rocm_problem.py
```

Both models converge fine on CPU (Threadripper 1950X):

```
env HIP_VISIBLE_DEVICES= python3 tf_rocm_problem.py
[...]
model1:
optimizer=<keras.optimizers.Adam object at 0x7fb95aa7d160>
Downloading data from https://s3.amazonaws.com/img-datasets/mnist.npz
11493376/11490434 [==============================] - 2s 0us/step
Train on 60000 samples, validate on 10000 samples
Epoch 1/1
2019-05-14 10:45:05.112599: E tensorflow/stream_executor/rocm/rocm_driver.cc:965] could not retrieve ROCM device count: HIP_ERROR_NoDevice
60000/60000 [==============================] - 43s 723us/step - loss: 0.0961 - acc: 0.9707 - val_loss: 0.0403 - val_acc: 0.9876

optimizer=<tensorflow.python.training.adam.AdamOptimizer object at 0x7fb9581bf7f0>
Train on 60000 samples, validate on 10000 samples
Epoch 1/1
60000/60000 [==============================] - 31s 511us/step - loss: 0.0978 - acc: 0.9703 - val_loss: 0.0366 - val_acc: 0.9887

model2:
optimizer=<keras.optimizers.Adam object at 0x7fb9502cb208>
Train on 60000 samples, validate on 10000 samples
Epoch 1/1
60000/60000 [==============================] - 20s 335us/step - loss: 0.1042 - acc: 0.9676 - val_loss: 0.0355 - val_acc: 0.9879

optimizer=<tensorflow.python.training.adam.AdamOptimizer object at 0x7fb950085c50>
Train on 60000 samples, validate on 10000 samples
Epoch 1/1
60000/60000 [==============================] - 24s 401us/step - loss: 0.0983 - acc: 0.9688 - val_loss: 0.0351 - val_acc: 0.9895
```

Both models converge fine on GPU (gfx803, Fiji, FuryX), too:

```
python3 tf_rocm_problem.py
[...]
model1:
optimizer=<keras.optimizers.Adam object at 0x7fa648960160>
Train on 60000 samples, validate on 10000 samples
Epoch 1/1
2019-05-14 10:49:11.949512: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1530] Found device 0 with properties: 
name: Device 7300
AMDGPU ISA: gfx803
memoryClockRate (GHz) 1
pciBusID 0000:09:00.0
Total memory: 4.00GiB
Free memory: 3.75GiB
2019-05-14 10:49:11.949653: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1530] Found device 1 with properties: 
name: Device 7300
AMDGPU ISA: gfx803
memoryClockRate (GHz) 1
pciBusID 0000:42:00.0
Total memory: 4.00GiB
Free memory: 3.75GiB
2019-05-14 10:49:11.949770: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1530] Found device 2 with properties: 
name: Device 7300
AMDGPU ISA: gfx803
memoryClockRate (GHz) 1.05
pciBusID 0000:43:00.0
Total memory: 4.00GiB
Free memory: 3.75GiB
2019-05-14 10:49:11.949811: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Adding visible gpu devices: 0, 1, 2
2019-05-14 10:49:11.949840: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1051] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-14 10:49:11.949853: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1057]      0 1 2 
2019-05-14 10:49:11.949868: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1070] 0:   N N N 
2019-05-14 10:49:11.949882: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1070] 1:   N N N 
2019-05-14 10:49:11.949892: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1070] 2:   N N N 
2019-05-14 10:49:11.949952: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1189] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3540 MB memory) -> physical GPU (device: 0, name: Device 7300, pci bus id: 0000:09:00.0)
2019-05-14 10:49:11.966810: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1189] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 3540 MB memory) -> physical GPU (device: 1, name: Device 7300, pci bus id: 0000:42:00.0)
2019-05-14 10:49:11.982826: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1189] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 3540 MB memory) -> physical GPU (device: 2, name: Device 7300, pci bus id: 0000:43:00.0)
2019-05-14 10:49:18.894177: I tensorflow/core/kernels/conv_grad_input_ops.cc:1023] running auto-tune for Backward-Data
2019-05-14 10:49:20.288789: I tensorflow/core/kernels/conv_grad_filter_ops.cc:975] running auto-tune for Backward-Filter
2019-05-14 10:49:22.391788: I tensorflow/core/kernels/conv_grad_filter_ops.cc:975] running auto-tune for Backward-Filter
60000/60000 [==============================] - 28s 472us/step - loss: 0.1067 - acc: 0.9670 - val_loss: 0.0906 - val_acc: 0.9859

optimizer=<tensorflow.python.training.adam.AdamOptimizer object at 0x7fa6481f66a0>
Train on 60000 samples, validate on 10000 samples
Epoch 1/1
60000/60000 [==============================] - 11s 180us/step - loss: 0.1010 - acc: 0.9690 - val_loss: 0.0478 - val_acc: 0.9861

model2:
optimizer=<keras.optimizers.Adam object at 0x7fa64804f278>
Train on 60000 samples, validate on 10000 samples
Epoch 1/1
60000/60000 [==============================] - 12s 207us/step - loss: 0.1012 - acc: 0.9693 - val_loss: 0.1558 - val_acc: 0.9817

optimizer=<tensorflow.python.training.adam.AdamOptimizer object at 0x7fa6380b1940>
Train on 60000 samples, validate on 10000 samples
Epoch 1/1
60000/60000 [==============================] - 10s 162us/step - loss: 0.1050 - acc: 0.9683 - val_loss: 0.0812 - val_acc: 0.9849
```

Note that Fiji, Polaris10 and Polaris11 are all covered by the gfx803.

**Comment by Bengt** [comment] 2019-05-14 12:56
To narrow the issue down further, I tested rocm 2.0 and Tensorflow 1.12, as requested by @sunway513:

```
$ docker run -it --device=/dev/kfd --device=/dev/dri --group-add video rocm/tensorflow:rocm2.0-tf1.12-python3
```

Both models converge fine on GPU:

```
# env HIP_VISIBLE_DEVICES= python3 tf_rocm_problem.py
[...]
model1:
optimizer=<keras.optimizers.Adam object at 0x7f8a0b34cd68>
Downloading data from https://s3.amazonaws.com/img-datasets/mnist.npz
11493376/11490434 [==============================] - 2s 0us/step
Train on 60000 samples, validate on 10000 samples
Epoch 1/1
2019-05-14 12:48:03.409213: E tensorflow/stream_executor/rocm/rocm_driver.cc:965] could not retrieve ROCM device count: HIP_ERROR_NoDevice
60000/60000 [==============================] - 44s 731us/step - loss: 0.0961 - acc: 0.9701 - val_loss: 0.0463 - val_acc: 0.9858

optimizer=<tensorflow.python.training.adam.AdamOptimizer object at 0x7f8a0825a6a0>
Train on 60000 samples, validate on 10000 samples
Epoch 1/1
60000/60000 [==============================] - 31s 510us/step - loss: 0.0964 - acc: 0.9702 - val_loss: 0.0366 - val_acc: 0.9894

model2:
optimizer=<keras.optimizers.Adam object at 0x7f8a00361438>
Train on 60000 samples, validate on 10000 samples
Epoch 1/1
60000/60000 [==============================] - 20s 332us/step - loss: 0.1063 - acc: 0.9668 - val_loss: 0.0374 - val_acc: 0.9881

optimizer=<tensorflow.python.training.adam.AdamOptimizer object at 0x7f8a001ba470>
Train on 60000 samples, validate on 10000 samples
Epoch 1/1
60000/60000 [==============================] - 24s 401us/step - loss: 0.1071 - acc: 0.9665 - val_loss: 0.0340 - val_acc: 0.9890
```

Both models converge fine on GPU, too:

```
root@65d9b2d48818:/root# python3 tf_rocm_problem.py
[...]
model1:
optimizer=<keras.optimizers.Adam object at 0x7f4aa6c1ee80>
Train on 60000 samples, validate on 10000 samples
Epoch 1/1
[...]
60000/60000 [==============================] - 28s 461us/step - loss: 0.1029 - acc: 0.9693 - val_loss: 0.0513 - val_acc: 0.9846

optimizer=<tensorflow.python.training.adam.AdamOptimizer object at 0x7f4b33c1af28>
Train on 60000 samples, validate on 10000 samples
Epoch 1/1
60000/60000 [==============================] - 11s 178us/step - loss: 0.1060 - acc: 0.9666 - val_loss: 0.0684 - val_acc: 0.9797

model2:
optimizer=<keras.optimizers.Adam object at 0x7f4b33bdda90>
Train on 60000 samples, validate on 10000 samples
Epoch 1/1
60000/60000 [==============================] - 12s 206us/step - loss: 0.1046 - acc: 0.9684 - val_loss: 0.1069 - val_acc: 0.9818

optimizer=<tensorflow.python.training.adam.AdamOptimizer object at 0x7f4b328b9cc0>
Train on 60000 samples, validate on 10000 samples
Epoch 1/1
60000/60000 [==============================] - 10s 161us/step - loss: 0.1018 - acc: 0.9682 - val_loss: 0.0899 - val_acc: 0.9780
```

**Comment by sunway513** [comment] 2019-06-08 05:50
Thank you @Bengt for the additional data points.
I can reproduce your observations on ROCm2.0 and ROCm2.1 based docker images, and validated it against the latest ROCm2.5 on GFX803 target. This issue should have been fixed since ROCm2.0, hence closing this issue.

**Closed by sunway513** 2019-06-08 05:50 UTC
Labels: bug, gfx803
