### ISSUE TITLE
Cannot install Tensorflow-Addons for TF-ROCm

### ISSUE THREAD

**Issue by quocdat32461997** [ROCmSoftwarePlatform/tensorflow-upstream#1082] opened 2020-08-19 02:29 UTC
**System information**
- Have I written custom code: No
- OS Platform and Distribution: Ubuntu 18
- TensorFlow installed from (source or binary): ROCM source
- TensorFlow version (use command below): TF-2.2
- Python version: 3.7
- GPU model and memory: Radeon VII 16Gb

**Describe the current behavior**
Installing Tensorflow-Addons raises error: "not finding a version that satisfies the requirement tensorflow-addons (from versions:) No matching distribution found for tensorflow-addons

**Describe the expected behavior**
Successfully install Tensorflow-Addons

**Standalone code to reproduce the issue**
pip3 install tensorflow-addons

**Comment by witeko** [comment] 2020-08-19 18:51
Sorry to cut in, but I think this is not a tensorflow-rocm issue. Maybe try installing addons from source?
Another route/angle: In my conda env "pip install tensorflow-addons" works just fine.

**Comment by quocdat32461997** [comment] 2020-08-19 20:01
> Sorry to cut in, but I think this is not a tensorflow-rocm issue. Maybe try installing addons from source?
> Another route/angle: In my conda env "pip install tensorflow-addons" works just fine.

Thanks. I’ll try and let you know.

**Comment by gsedej** [comment] 2020-08-26 12:41
I found this issue when trying some tensorflow models examples and come to similar issue 
(https://github.com/tensorflow/models/tree/master/official/vision/image_classification ResNet50)

pip install tensorflow-addons does not work for me.
When I try this on my "rocm" virtual envrioment it says
```
$ pip3 install tensorflow-addons
Collecting tensorflow-addons
  Cache entry deserialization failed, entry ignored
  Could not find a version that satisfies the requirement tensorflow-addons (from versions: )
No matching distribution found for tensorflow-addons
```

but when using "standard" tensorflow venv (cpu-only in my case)
```
$ pip3 install tensorflow-addons
Requirement already satisfied: tensorflow-addons in ./tf2venv/lib/python3.6/site-packages (0.11.1)
Requirement already satisfied: typeguard>=2.7 in ./tf2venv/lib/python3.6/site-packages (from tensorflow-addons) (2.9.1)
```

Probably addons package is not yet updated for tensorflow-rocm 2.3. Might be wrong.

**Comment by jerryyin** [comment] 2020-08-28 20:39
Cannot reproduce in ROCm3.7 docker, closing now.

$ ~ docker pull rocm/tensorflow-autobuilds:rocm3.7-latest 
> rocm3.7-latest: Pulling from rocm/tensorflow-autobuilds
> ...
> docker.io/rocm/tensorflow-autobuilds:rocm3.7-latest

$ ~ drun rocm/tensorflow-autobuilds:rocm3.7-latest   
$ pip3 install tensorflow-Addons
> Collecting tensorflow-Addons
  Downloading tensorflow_addons-0.11.2-cp36-cp36m-manylinux2010_x86_64.whl (1.1 MB)
     |################################| 1.1 MB 6.1 MB/s 
Collecting typeguard>=2.7
  Downloading typeguard-2.9.1-py3-none-any.whl (16 kB)
Installing collected packages: typeguard, tensorflow-Addons
Successfully installed tensorflow-Addons-0.11.2 typeguard-2.9.1

**Closed as completed by jerryyin** 2020-08-28 20:39 UTC

**Comment by gsedej** [comment] 2020-08-31 10:30
Can confirm it works for me. I had to upgrade "pip"  via `pip3 install pip --upgrade˙`.

After that you can install tensorflow-addons
