### ISSUE TITLE
(0) Invalid argument: Input to reshape is a tensor with 0 values, but the requested shape has 169344

### ISSUE THREAD

**Issue by XuanBaby** [ROCmSoftwarePlatform/tensorflow-upstream#767] opened 2019-12-21 23:16 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
I use the images rocm/tensorflow:rocm2.10.0-tf1.14-dev
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):images
- TensorFlow version (use command below):tf1.14
- Python version:3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- ROCm/MIOpen version:rocm2.10
- GPU model and memory:gfx906/16g
-HOROVOD :0.18.1

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I run the FastRCNN examples which under the [tensorpack](https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/train.py)
python3 train.py 
I have already ask the question in [_tesnorpack-issue_](https://github.com/tensorpack/tensorpack/issues/1373)  ,maybe is a bug from tensorflow,can you give me some advices?

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
the log which I change the code to train is gitdiff
[diff-log.txt](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/3991922/diff-log.txt)
the log which contain error is 
[xuan-docker-v1.log](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/3991924/xuan-docker-v1.log)

**Comment by sebpuetz** [comment] 2019-12-22 15:19
Probably #325, should be fixed in ROCm 3.0?

**Comment by XuanBaby** [comment] 2019-12-23 04:12
@sebpuetz  I run the program use imges:rocm/tensorflow:rocm3.0-tf1.14-python3,the same error 
[xuan-rocm3.0-4dcu.log](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/3993604/xuan-rocm3.0-4dcu.log)

**Comment by sunway513** [comment] 2019-12-30 01:28
> @sebpuetz I run the program use imges:rocm/tensorflow:rocm3.0-tf1.14-python3,the same error
> [xuan-rocm3.0-4dcu.log](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/3993604/xuan-rocm3.0-4dcu.log)

Hi @XuanBaby , in your new log there's no longer messages w.r.t. `Invalid argument: Input to reshape` error, hence the original issue might have been fixed in ROCm3.0 docker container. 
Can you list the exact steps to reproduce your issue?
cc @jeffdaily

**Comment by XuanBaby** [comment] 2019-12-31 02:51
Hi @sunway513  I did not change the code,just run it in images:rocm/tensorflow:rocm3.0-tf1.14-python3.  reshape error not found but in the two logs ,the traceback information are same,
 in addition ,about the warrning  `W tensorflow/core/kernels/queue_base.cc:277] _0_QueueInput/input_queue: Skipping cancelled enqueue attempt with queue not closed`  Why the warning? could you give me some guides?

**Comment by jeffdaily** [comment] 2020-01-02 15:51
I see from the initial issue report that you are using horovod, and I also confirm from the latest log that you are running using mpirun (again, for horovod).
```
[2019-12-23 02:33:32.389346: W horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for     more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock.
```
How did you install horovod?  From the main repo?  Our fork/branch?

**Comment by XuanBaby** [comment] 2020-01-07 02:43
Hi @jeffdaily ,about horovod,I try two way to install,
One isuse the [horovod/horovod](https://github.com/horovod/horovod),default, `HOROVOD_GPU_ALLREDUCE=MPI HOROVOD_GPU_ALLGATHER=MPI HOROVOD_GPU_BROADCAST=MPI HOROVOD_GPU_ROCM=True HOROVOD_WITHOUT_GLOO=1 HOROVOD_CPU_OPERATIONS=MPI HOROVOD_WITHOUT_MXNET=1 HOROVOD_WITHOUT_PYTORCH=1 HOROVOD_WITH_TENSORFLOW=1 python3 setup.py install`
the other is [ROCmSoftwarePlatform/horovod](https://github.com/ROCmSoftwarePlatform/horovod)
-b hip
`HOROVOD_NCCL_LINK=SHARED HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_NCCL_HOME=/opt/rocm/rccl/ HOROVOD_GPU_ROCM=1 HOROVOD_WITHOUT_GLOO=1 HOROVOD_CPU_OPERATIONS=MPI HOROVOD_WITHOUT_MXNET=1 HOROVOD_WITHOUT_PYTORCH=1 HOROVOD_WITH_TENSORFLOW=1 python3 setup.py install`
they all could cause the problems.

**Comment by jeffdaily** [comment] 2020-01-07 16:48
Thank you for providing more details.  I will try and reproduce.

Note that when using https://github.com/horovod/horovod, it will ignore the `HOROVOD_GPU_ROCM=1` setting -- we haven't yet had our upstreaming PR approved and merged.

You may continue to try using https://github.com/ROCmSoftwarePlatform/horovod, either the `hip` branch or the newer `hip-pimpl` branch.  These two hip branches in our fork are the two attempts thus far at upstreaming ROCm support and behave similarly.  The `hip` branch has been rejected by upstream and we have an ongoing discussion how to move forward with upstreaming ROCm support.

**Comment by XuanBaby** [comment] 2020-01-10 02:02
@jeffdaily Thank you for your help .
and about [https://github.com/ROCmSoftwarePlatform/horovod](url) I have another question,when I try use pytorch & horovod ,I can install pytorch and horovod together,but when I run the [horovod/examples](https://github.com/ROCmSoftwarePlatform/horovod/blob/hip/examples/pytorch_imagenet_resnet50.py),the error bellow:
`Traceback (most recent call last):
  File "pytorch_imagenet_resnet50.py", line 157, in <module>
    hvd.broadcast_parameters(model.state_dict(), root_rank=0)
  File "/public/home/yangxuan1/Pytorch/Python3.6.8/lib/python3.6/site-packages/horovod-0.18.1-py3.6-linux-x86_64.egg/horovod/torch/__init__.py", line 279, in broadcast_parameters
    handle = broadcast_(p, root_rank, name)
  File "/public/home/yangxuan1/Pytorch/Python3.6.8/lib/python3.6/site-packages/horovod-0.18.1-py3.6-linux-x86_64.egg/horovod/torch/mpi_ops.py", line 409, in broadcast_
    handle = broadcast_async_(tensor, root_rank, name)
  File "/public/home/yangxuan1/Pytorch/Python3.6.8/lib/python3.6/site-packages/horovod-0.18.1-py3.6-linux-x86_64.egg/horovod/torch/mpi_ops.py", line 387, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name)
  File "/public/home/yangxuan1/Pytorch/Python3.6.8/lib/python3.6/site-packages/horovod-0.18.1-py3.6-linux-x86_64.egg/horovod/torch/mpi_ops.py", line 297, in _broadcast_async
    tensor, output, root_rank, name.encode() if name is not None else _NULL)
RuntimeError: Internal error. Requested ReadyEvent with GPU device but not compiled with CUDA.`
could you give me some advice? thank you very much!

**Comment by jeffdaily** [comment] 2020-01-10 15:48
@XuanBaby That is because we have not yet enabled Horovod with PyTorch.  The build will succeed because the CUDA code in the horovod/torch directory is conditionally compiled, but the non-CUDA path that you are getting will simply error out as you have encountered.  ROCm+PyTorch+Horovod is in development.

**Comment by XuanBaby** [comment] 2020-01-13 09:20
@jeffdaily  when will it be supported? do you have the roadmap about it?

**Comment by jeffdaily** [comment] 2020-01-28 22:58
Before Horovod PyTorch is fully supported, we need improved support for `torch/utils/cpp_extensions.py` for building ROCm PyTorch extensions such as Horovod.  The PR tracking that progress is https://github.com/pytorch/pytorch/pull/32669.

If you were to build the PyTorch branch that the PR is based on (https://github.com/ashishfarmer/pytorch/tree/af/hipext), you could then build our Horovod branch that adds PyTorch support.  That branch is https://github.com/ROCmSoftwarePlatform/horovod/tree/hipify-pytorch.

**Comment by jeffdaily** [comment] 2020-02-18 17:39
Closing this ticket since the original issue is resolved, `Invalid argument: Input to reshape`.  Please open a new ticket for any additional issues.  Thanks.

**Closed by jeffdaily** 2020-02-18 17:39 UTC
