### ISSUE TITLE
ROCm/CUDA mismatch for where op

### ISSUE THREAD

**Issue by ekuznetsov139** [ROCmSoftwarePlatform/tensorflow-upstream#614] opened 2019-08-26 18:30 UTC
```
from __future__ import print_function
import tensorflow as tf
v=[True,  True,  True, False,  True,  True,  True, False,  True,  True,  True, False,  True,  True,  True, False]
tf.enable_eager_execution()
v = tf.convert_to_tensor(v, dtype=tf.bool)
w = tf.where(v)
print(w)
```

With CUDA-backed Tensorflow, I get
```
tf.Tensor(
[[ 0]
 [ 1]
 [ 2]
 [ 4]
 [ 5]
 [ 6]
 [ 8]
 [ 9]
 [10]
 [12]
 [13]
 [14]], shape=(12, 1), dtype=int64)
```
(which is as expected.) 

With ROCm, I get

```tf.Tensor([[12]], shape=(1, 1), dtype=int64)```

Observed with master tensorflow and ROCm 2.7. (Will retest with this branch when I can, but stupid tensorflow takes 3 hours to recompile, so, would appreciate it if someone tested it for me with this branch.)

**Comment by whchung** [comment] 2019-08-29 01:14
A PR to change TensorFlow build system to take both `rocprim` and `hipcub` from ROCm 2.7+ has been submitted:

https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/620

On a standard ROCm 2.7 installation, doing the following steps would make the test to work:

1) apt install hipcub rocprim
2) cherry-pick the commit in #620 
3) rebuild TensorFlow from source.

**Comment by ekuznetsov139** [comment] 2019-08-29 02:46
I don't think it is a good idea to let tensorflow use systemwide rocprim and hipcub in the first place. It should check out known good versions as part of the build process and use those.

**Comment by whchung** [comment] 2019-08-29 18:18
@ekuznetsov139 In general TensorFlow uses systemwide ROCm libraries by default. `rocprim` and `hipcub` is the exception here. I'll check with maintainers of `rocprim` and `hipcub` on how to better catch issues like this before a new release is published.

**Comment by whchung** [comment] 2019-08-30 15:02
@ekuznetsov139 We'll fix the packaging issue so both `rocprim` and `hipcub` are shipped along with ROCm release. And they will be quality checked by frameworks such as TensorFlow to ensure no regression moving forward.

Here's an example where_op is working fine on ROCm CI:
http://ml-ci.amd.com:21096/job/tensorflow-upstream-unit-tests/1346/console
```
//tensorflow/python/kernel_tests:where_op_test_gpu                       [0m[32mPASSED[0m in 49.6s
```

Since we have a short-term workaround, and a long-term solution, I'm closing this ticket hereby.

**Closed by whchung** 2019-08-30 15:02 UTC
Labels: math lib

**Comment by ekuznetsov139** [comment] 2019-08-30 21:54
What is the long-term solution? We've established that rocprim from 2.7 does not work correctly, and there have been no commits to fix it, and instead we have a change to pin TF-ROCm permanently to that broken version of rocprim. Am I missing something?

The link you provided gives me a 404 Not Found error. The only projects I see on that Jenkins are tensorflow-rocm-nightly, tensorflow-rocm-release, tensorflow-rocm-v2-nightly, and tensorflow-rocm-v2-release. No tensorflow-upstream-unit-tests.

**Comment by whchung** [comment] 2019-08-31 01:42
Long term solution would be in the upcoming ROCm 2.8. rocprim and hipcub would be tested by TensorFlow via the unit test aforementioned.

For ROCm 2.7, please stick with the short term solution (uninstall rocprim). Alternatively, you may want to install hipcub package, cherry pick #620, and rebuild TF.
