### ISSUE TITLE
Tensorpack FasterRCNN Memory access fault by GPU node-1 ... Reason: Page not present or supervisor privilege.

### ISSUE THREAD

**Issue by numPlumber** [ROCmSoftwarePlatform/tensorflow-upstream#301] opened 2019-01-27 03:09 UTC
**System information**
- Custom code: Installed tensorpack from github rather than the package due to a lack of update to msgpack params that led to an error.  Commented out lines 484, 491, 492 in train.py to prevent calls to nvidia performance tracking.
- OS: Linux Ubuntu 18.04
- TensorFlow installed binary
- TensorFlow version: v1.12.0-871-gf480b4a 1.12.0
- Python version: Python 3.6.7 
- GPU model and memory:
name: Ellesmere [Radeon RX 470/480]
AMDGPU ISA: gfx803
memoryClockRate (GHz) 1.15
pciBusID 0000:01:00.0
Total memory: 8.00GiB
Free memory: 7.75GiB

**Describe the current behavior**
Memory access fault by GPU node-1 (Agent handle: 0x2b68910) on address 0xadca1b000. Reason: Page not present or supervisor privilege.
- Usually comes up on first training iteration, but it has made it to 8 iterations before showing the error message.  I assume the variance is due to the randomization of the training data.

**Describe the expected behavior**
Not getting a fault

**Code to reproduce the issue**
python3 train.py --config MODE_MASK=True MODE_FPN=True DATA.BASEDIR=/.../COCO/DIR BACKBONE.WEIGHTS=/.../ImageNet-R50-AlignPadding.npz
COCO
└── DIR
    ├── annotations - captions_train2014.json  instances_minival2014.json  instances_val2014.json person_keypoints_train2014.json captions_val2014.json instances_train2014.json instances_valminusminival2014.json  person_keypoints_val2014.json
    ├── train2014
    └── val2014

Let me know what logs and debug params you want me to include.  I looked at similar issues in an attempt to fix the problem.  Nothing solved my issue, however, I did run all the tensorflow models that were suggested for other issues and they all worked.

**Comment by sunway513** [comment] 2019-01-27 03:46
Hi @numPlumber , can you provide the FasterRCNN repo you've been using? I'll try to repro the failure locally.
Besides, the failure signature looks similar to issue #282 and #300. We are investigating the root cause.

**Comment by numPlumber** [comment] 2019-01-27 06:13
https://github.com/tensorpack/tensorpack
Master branch
Go to examples/FasterRCNN

**Comment by witeko** [comment] 2019-01-27 11:47
Same error in https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/297

**Comment by numPlumber** [comment] 2019-01-27 20:01
Clarification regarding tensorpack install process:
The tensorpack PyPI install process didn't include updated code for tensorpack/utils/serialize.py which let to an error with msgpack. Thus, I installed via: "pip3 install git+https://github.com/tensorpack/tensorpack.git"
That commit number is 21c494697faa40db0e280a3c53abad2521b2e1f6

**Comment by sunway513** [comment] 2019-01-27 20:10
@numPlumber , I've installed it as well. However, tensorpack has dependencies on NVML library, which prevents me from running the FasterRCNN training on ROCm at the runtime.

**Comment by numPlumber** [comment] 2019-01-27 20:21
Commenting out lines 484, 491, 492 in ../FasterRCNN/train.py didn't take care of that?

**Comment by sunway513** [comment] 2019-01-27 20:33
Thanks @numPlumber , I've hacked train.py, config.py and callbacks/prof.py, now the training is moving. Will let you know how it goes.

**Comment by numPlumber** [comment] 2019-01-27 20:34
What did you change in config.py and prof.py?

**Comment by sunway513** [comment] 2019-01-27 20:39
Hmm, it still failed after TF auto-tuning session due to the NVML dependancy. 
Since your issue is similar to #282 (vmem access fault on Polaris GPUs), I'll use that to continue the investigation. Will keep you updated if we have any workarounds or fixes for the issue.

**Comment by numPlumber** [comment] 2019-01-27 20:43
Can you post the traceback?

**Comment by sunway513** [comment] 2019-02-07 19:13
@numPlumber , any feedback on the suggested workaround?

**Comment by geekboood** [comment] 2019-04-07 14:05
@sunway513 I encounter the same issue when I train my semantic segmentation model. Reinstall the opencl package fixed the issue first time, however, when I rerun my program, I need to clear the MIOpen cache to get it run normally. Is that normal?

**Comment by sunway513** [comment] 2019-04-07 18:26
Hi @geekboood , It's required to clean the MIOpen cache after each time MIOpen library got updated. Otherwise, MIOpen library would just use the old kernel binary compiled with the faulty toolchain.

**Comment by sunway513** [comment] 2019-06-08 05:55
Hi @numPlumber, @geekboood , we have included a set of OCL toolchain fixes for GFX803 targets in ROCm2.5, please kindly try it and let us know if that helps with the issue.

**Comment by sunway513** [comment] 2019-06-14 15:25
I'm closing this issue as it has been fixed in ROCm2.5.

**Closed by sunway513** 2019-06-14 15:25 UTC
Labels: bug, gfx803
