### ISSUE TITLE
ResourceExhaustedError 580X

### ISSUE THREAD

**Issue by alexja14** [ROCmSoftwarePlatform/tensorflow-upstream#235] opened 2018-11-10 22:17 UTC
**System information**
- Hi i used custom script : https://github.com/lengstrom/fast-style-transfer
- Using ubuntu 18.04.01
- TensorFlow installed pip3 install --user tensorflow-rocm
- TensorFlow version 1.11.0'
- Python version 3.6.5

- GPU model and memory:
 *-display                 
       description: VGA compatible controller
       product: Ellesmere [Radeon RX 470/480]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:09:00.0
       version: e7
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=amdgpu latency=0
       resources: irq:85 memory:e0000000-efffffff memory:f0000000-f01fffff ioport:e000(size=256) memory:fe900000-fe93ffff memory:c0000-dffff
----------------------------------------------------------------
BUT ITS A AMD  580 X
-----------------------------------

**Describe the current behavior**
I'm running a custom script on python 3.. for a style transfer project.. I want to train a model.. After a couple of seconds of training it crashes. 

The dataset is around 80 k fotos.

Can you guys give me a hand  ? I uploaded the log . 

Thank you again . 

**Other info / logs**
[Dropped Text.txt](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/2568837/Dropped.Text.txt)

**Comment by pricebenjamin** [comment] 2018-11-10 22:45
```
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[20,65536,64]
```

You're going to need to decrease your batch size. Try a batch size of 1, 2, or 4. If that doesn't work, you're going to need to resize your input images, which may require further modifications to the network.

**Comment by alexja14** [comment] 2018-11-11 12:15
@pricebenjamin thank you for your feedback. I made a lower batch size .. But now i get this error : 

python/client/session.py", line 1312, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'save/SaveV2': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Registered kernels:
  device='CPU'





I tried to add : 
tf.Session(config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=True))

But it didn't change really anything .. do you have any clue on how to fix this ? 

Kindly Regards,
Alex

**Comment by sunway513** [comment] 2019-01-02 21:42
@alexja14 , could you provide us with the exact foolproof steps to repro your issue?

**Comment by sunway513** [comment] 2019-02-07 22:32
I'll close this ticket as it has been stalled. @alexja14 please let us know if the issue is still reproducible with the latest TF environment.

**Closed by sunway513** 2019-02-07 22:32 UTC
